#!/usr/bin/env bash

USER=neuroidss
NAME=ray-python-ubuntu

#for arch in amd64; do
#for arch in arm64; do
#for arch in amd64 arm64 arm riscv64; do
for arch in amd64 arm64; do
#  docker buildx build --platform linux/${arch} -f Dockerfile.${arch} -t $USER/$NAME:${arch}-20.04 . --push
  docker buildx build --platform linux/${arch} -f Dockerfile.${arch} -t $USER/$NAME:${arch}-22.04 . --push
#  docker build -f Dockerfile.${arch} -t $USER/$NAME:${arch}-22.04 .
#  docker build -f Dockerfile.${arch} -t $USER/$NAME:${arch}-20.04 .
  
#  docker buildx build --progress plain --platform linux/${arch} -f Dockerfile.${arch} -t $USER/$NAME:${arch}-20.04 . --push
done
